# Generated by Django 4.2.2 on 2023-06-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nomi', max_length=123)),
                ('phone_number', models.CharField(help_text='Telefon raqami', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='Email', max_length=100, unique=True)),
                ('checked', models.BooleanField(default=False, help_text='Tekshirilganmi?')),
                ('text', models.TextField(help_text='Matn')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Sana')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_looms', models.CharField(help_text='считать ткацкие станки', max_length=123)),
                ('experience', models.CharField(help_text='опыт', max_length=123)),
                ('bir_kunlik_chiqim', models.CharField(help_text='тонн сырья в сутки', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Назначение', max_length=123)),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.PositiveIntegerField()),
                ('composition', models.CharField(help_text='Состав:', max_length=123)),
                ('weight', models.CharField(help_text='Плотность', max_length=123)),
                ('width', models.CharField(help_text='Ширина', max_length=123)),
                ('length_per_kg', models.CharField(help_text='Длина на кг', max_length=123)),
                ('minimum_order', models.CharField(help_text='Минимальный заказ', max_length=123)),
                ('delivery_time', models.CharField(help_text='Срок поставки', max_length=123)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
    ]
