# Generated by Django 4.2.2 on 2023-06-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='email',
        ),
        migrations.AddField(
            model_name='application',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='application_images/'),
        ),
    ]
